spring:
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      uri: mongodb://root:root@mongo:27017/call-service?authSource=admin
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}

app:
  kafka:
    enabled: ${APP_KAFKA_ENABLED:true}
  service:
    identity: http://identity:8080/identity
    notification: http://notification:8082/notification
