spring.config.activate.on-profile=docker

spring.datasource.url=jdbc:postgresql://postgres:5432/post

spring.data.redis.host=${REDIS_HOST:cool-zebra-153037.upstash.io}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.username=${REDIS_USERNAME:default}
spring.data.redis.password=${REDIS_PASSWORD:}
spring.data.redis.ssl.enabled=${REDIS_SSL:true}

app.services.identity=http://identity:8080/identity/user
app.services.profile=http://profile:8081/profile/
app.services.notification=http://notification:8082/notification
app.services.ai=http://ai-server:5000/check-post
