spring.config.activate.on-profile=docker

spring.mongodb.uri=mongodb://root:root@mongo:27017/stories?authSource=admin

spring.data.redis.host=${REDIS_HOST:top-trout-153046.upstash.io}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.username=${REDIS_USERNAME:default}
spring.data.redis.password=${REDIS_PASSWORD:}
spring.data.redis.ssl.enabled=${REDIS_SSL:true}

app.services.identity=http://identity:8080/identity/user
app.services.profile=http://profile:8081/profile/
